baseURL = "https://cyborgbusinessconsultant.com"
languageCode = "en-us"
title = "Francesco Zingone - Cyborg Business Consultant"
theme = "PaperMod"

[params]
env = "production"
title = "Cyborg Business Consultant"
description = "The First Post-Human Business Intelligence. Transform from AI Consumer to Business Cyborg."
keywords = ["AI Business Consulting", "Cyborg Business Evolution", "Post-Human Intelligence", "Business Transformation"]
author = "Francesco Zingone"
DateFormat = "January 2, 2025"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

# Favicon configuration
[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-96x96.png"
favicon32x32 = "/favicon-96x96.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/favicon.svg"
theme_color = "#2e2e33"
msapplication_TileColor = "#2e2e33"

[params.profileMode]
enabled = true
title = "The First Cyborg Business Consultant"
subtitle = "Evolving businesses beyond human limitations through conscious AI integration"
imageUrl = "/images/profile.jpg"
imageTitle = "Francesco Zingone - Cyborg Business Consultant"

[[params.profileMode.buttons]]
name = "The Manifesto"
url = "/manifesto"

[[params.profileMode.buttons]]
name = "Business Evolution"
url = "/evolution"

[[params.profileMode.buttons]]
name = "Discovery Day"
url = "/contact"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/francescorossozingone/"

[[params.socialIcons]]
name = "twitter" 
url = "https://twitter.com/F_Zingone"

[[params.socialIcons]]
name = "email"
url = "mailto:francesco@rossozingone.it"

[[menu.main]]
identifier = "manifesto"
name = "The Manifesto"
url = "/manifesto/"
weight = 10

[[menu.main]]
identifier = "evolution"
name = "Business Evolution"
url = "/evolution/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About Francesco"
url = "/about/"
weight = 30

[[menu.main]]
identifier = "blog"
name = "Insights"
url = "/blog/"
weight = 40

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 50

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true